name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag simurlacra
      - name: Execute tests
        run: |
          mkdir cov
          docker run --rm -i --mount type=bind,source="$(pwd)"/cov,target=/home/user/cov \ simurlacra conda run -n pyrado bash -c "pytest Pyrado/tests/ --cov=/home/user/cov --cov-report=xml --verbose -m 'not visualisation and not longtime'"
