name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag simurlacra
      - name: Execute tests
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        run: |
          wget https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          chmod +x test-reporter-latest-linux-amd64
          ./test-reporter-latest-linux-amd64 before-build
          docker run --rm -i -v $(pwd):/cov simurlacra conda run -n pyrado bash -c "pytest Pyrado/tests --cov=./Pyrado --cov-report=xml --verbose -m 'not visualization and not longtime' || mv coverage.xml /cov"
          ./test-reporter-latest-linux-amd64 after-build -t coverage.py
