name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag simurlacra
      - name: Execute tests
        run: |
          docker run --rm -i -v $(pwd):/cov simurlacra conda run -n pyrado bash -c "pytest Pyrado/tests --cov=Pyrado --cov-report=xml --verbose -m 'not visualization and not longtime'; cat coverage.xml; mv coverage.xml /cov"
      - uses: codecov/codecov-action@v1
        with:
          file: coverage.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
